### ISSUE TITLE
Animation not working on Android

### ISSUE THREAD

**Issue by IkaroAlef** [martinslapinskis/react-native-chi-page-control#2]
First, I'd like to thank you for this lib!
I'm using PageControlPoblano with default settings, but there is no animation. Any tips on how can I fix this?

EXPO SDK 39
RN 0.63
Android 10.

**Comment by martinslapinskis** [comment]
Hi @IkaroAlef, I tried to run project with [sample code](https://github.com/martinslapinskis/react-native-chi-page-control/blob/master/examples/FlatListExample.js) on Android 10 (API 29) emulator, but everything was working. my packages:

```
  "dependencies": {
    "expo": "~39.0.2",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz",
    "react-native-chi-page-control": "0.0.4",
    "react-native-web": "~0.13.12"
  },
```
Maybe you could provide more information to investigate it deeper, like if it is only on Android 10 or what device are you using or if it is on real device?

**Comment by martinslapinskis** [comment]
There was not provided enough information that is why I am closing this issue.
